cloud:
  aws:
    credentials:
      secret-key: 4Aiu9Pja46fkt4moDwH4XpFcjrFnmT5yE+5JJQ6Z
      access-key: AKIAT36Y7MRMY4Q7QQIT
    s3:
      bucket:
        nodeValue: gongzonebucket
        url: https://s3.ap-northeast-2.amazonaws.com/gongzonebucket
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'
spring:
  data:
    jpa:
      repositories:
        enabled: 'true'
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: scott
    url: jdbc:mysql://localhost:3306/gongzone