spring:
  data:
    jpa:
      repositories:
        enabled: 'true'
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: scott
    url: jdbc:mysql://localhost:3306/gongzone

