spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scott
    username: scott
    password: tiger
  
  jpa:
    open-in-view : 'false'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: none
    show-sql: "true"

  profiles:
    include:
      - aws
      - credentials

logging:
  level:
    com.gonzone: debug

jwt:
  secret: YmFsbG9vbi1wcm9qZWN0LWFpci13ZS1tYWRlLW1lc3Nlbmdlci1jYWxlbmRhci1lbGVjdHJvbmljQXBwcm92YWwtc3ByaW5nLXNlY3VyaXR5

# Swagger 
spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
springdoc.swagger-ui.path: /api-document.html
springdoc.cache.disabled: true
springdoc.override-with-generic-response: false
springdoc:
  api-docs:
    path: /api/v1/api-docs