spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gongzone-db.cmjrreikybyw.ap-northeast-2.rds.amazonaws.com:3306/gongzone
    username: gongzone
    password: gongzone123

  jpa:
    open-in-view: "false"
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: none
    show-sql: "true"

  profiles:
    include:
      - aws
      - credentials

logging:
  path: ./
  level:
    com.gonzone: debug

jwt:
  secret: YmFsbG9vbi1wcm9qZWN0LWFpci13ZS1tYWRlLW1lc3Nlbmdlci1jYWxlbmRhci1lbGVjdHJvbmljQXBwcm92YWwtc3ByaW5nLXNlY3VyaXR5

# Swagger
spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
springdoc.swagger-ui.path: /api/api-document.html
springdoc.cache.disabled: true
springdoc.override-with-generic-response: false
springdoc:
  api-docs:
    path: /api/v1/api-docs

# AWS
cloud:
  aws:
    s3:
      bucket: gongzone1bucket
    region:
      static: ap-northeast-2
    stack:
      auto: "false"
    credentials:
      instanceProfile: "true"
      accessKey: AKIAT36Y7MRMQOJQ7UWR
      secretKey: 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